/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  Lightbulb,
  LightbulbInterface,
} from "../../../contracts/L1/Lightbulb";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_veaOutbox",
        type: "address",
      },
      {
        internalType: "address",
        name: "_lightBulbSwitch",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "lightBulbIsOn",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lightBulbSwitch",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_msgSender",
        type: "address",
      },
      {
        internalType: "address",
        name: "lightBulbOwner",
        type: "address",
      },
    ],
    name: "turnOn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "veaOutbox",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60c060405234801561001057600080fd5b506040516103b23803806103b283398101604081905261002f91610062565b6001600160a01b039182166080521660a052610095565b80516001600160a01b038116811461005d57600080fd5b919050565b6000806040838503121561007557600080fd5b61007e83610046565b915061008c60208401610046565b90509250929050565b60805160a0516102ec6100c6600039600081816056015261018401526000818160e2015261011001526102ec6000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630c5ecbd21461005157806345fbb5ed14610095578063501ea4e1146100aa578063dea580b9146100dd575b600080fd5b6100787f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b0390911681526020015b60405180910390f35b6100a86100a3366004610261565b610104565b005b6100cd6100b8366004610294565b60006020819052908152604090205460ff1681565b604051901515815260200161008c565b6100787f000000000000000000000000000000000000000000000000000000000000000081565b81336001600160a01b037f000000000000000000000000000000000000000000000000000000000000000016146101825760405162461bcd60e51b815260206004820152601960248201527f4c3120417574683a204f6e6c7920566561204272696467652e0000000000000060448201526064015b60405180910390fd5b7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316816001600160a01b03161461021f5760405162461bcd60e51b815260206004820152603360248201527f4c3220417574683a204f6e6c7920746865207377697463682063616e20747572604482015272371037b7103a3432903634b3b43a313ab6311760691b6064820152608401610179565b506001600160a01b03166000908152602081905260409020805460ff1916600117905550565b80356001600160a01b038116811461025c57600080fd5b919050565b6000806040838503121561027457600080fd5b61027d83610245565b915061028b60208401610245565b90509250929050565b6000602082840312156102a657600080fd5b6102af82610245565b939250505056fea2646970667358221220ca425c421f7fc7611f13604b7f19bd747a9fae86a27839930ed2fdb2a3d284dc64736f6c63430008120033";

type LightbulbConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LightbulbConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Lightbulb__factory extends ContractFactory {
  constructor(...args: LightbulbConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _veaOutbox: string,
    _lightBulbSwitch: string,
    overrides?: Overrides & { from?: string }
  ): Promise<Lightbulb> {
    return super.deploy(
      _veaOutbox,
      _lightBulbSwitch,
      overrides || {}
    ) as Promise<Lightbulb>;
  }
  override getDeployTransaction(
    _veaOutbox: string,
    _lightBulbSwitch: string,
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(
      _veaOutbox,
      _lightBulbSwitch,
      overrides || {}
    );
  }
  override attach(address: string): Lightbulb {
    return super.attach(address) as Lightbulb;
  }
  override connect(signer: Signer): Lightbulb__factory {
    return super.connect(signer) as Lightbulb__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LightbulbInterface {
    return new utils.Interface(_abi) as LightbulbInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Lightbulb {
    return new Contract(address, _abi, signerOrProvider) as Lightbulb;
  }
}
