/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface LightbulbInterface extends utils.Interface {
  functions: {
    "lightBulbIsOn(address)": FunctionFragment;
    "lightBulbSwitch()": FunctionFragment;
    "turnOn(address,address)": FunctionFragment;
    "veaOutbox()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "lightBulbIsOn"
      | "lightBulbSwitch"
      | "turnOn"
      | "veaOutbox"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "lightBulbIsOn",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "lightBulbSwitch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "turnOn",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "veaOutbox", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "lightBulbIsOn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lightBulbSwitch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "turnOn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "veaOutbox", data: BytesLike): Result;

  events: {};
}

export interface Lightbulb extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LightbulbInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    lightBulbIsOn(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    lightBulbSwitch(overrides?: CallOverrides): Promise<[string]>;

    turnOn(
      _msgSender: string,
      lightBulbOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    veaOutbox(overrides?: CallOverrides): Promise<[string]>;
  };

  lightBulbIsOn(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  lightBulbSwitch(overrides?: CallOverrides): Promise<string>;

  turnOn(
    _msgSender: string,
    lightBulbOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  veaOutbox(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    lightBulbIsOn(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    lightBulbSwitch(overrides?: CallOverrides): Promise<string>;

    turnOn(
      _msgSender: string,
      lightBulbOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    veaOutbox(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    lightBulbIsOn(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    lightBulbSwitch(overrides?: CallOverrides): Promise<BigNumber>;

    turnOn(
      _msgSender: string,
      lightBulbOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    veaOutbox(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    lightBulbIsOn(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lightBulbSwitch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    turnOn(
      _msgSender: string,
      lightBulbOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    veaOutbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
