/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IVeaInbox",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVeaInbox__factory>;
    getContractFactory(
      name: "ILightBulb",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILightBulb__factory>;
    getContractFactory(
      name: "Lightbulb",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lightbulb__factory>;
    getContractFactory(
      name: "Switch",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Switch__factory>;

    getContractAt(
      name: "IVeaInbox",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IVeaInbox>;
    getContractAt(
      name: "ILightBulb",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILightBulb>;
    getContractAt(
      name: "Lightbulb",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Lightbulb>;
    getContractAt(
      name: "Switch",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Switch>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
