/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as kleros from "./@kleros";
export type { kleros };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { IVeaInbox } from "./@kleros/vea-contracts/interfaces/inboxes/IVeaInbox";
export { IVeaInbox__factory } from "./factories/@kleros/vea-contracts/interfaces/inboxes/IVeaInbox__factory";
export type { ILightBulb } from "./contracts/interfaces/ILightBulb";
export { ILightBulb__factory } from "./factories/contracts/interfaces/ILightBulb__factory";
export type { Lightbulb } from "./contracts/L1/Lightbulb";
export { Lightbulb__factory } from "./factories/contracts/L1/Lightbulb__factory";
export type { Switch } from "./contracts/L2/Switch";
export { Switch__factory } from "./factories/contracts/L2/Switch__factory";
